### ISSUE TITLE
Python-3 port?

### ISSUE THREAD

**Issue by khurshid-alam** [poulp/zenipy#15]
Is there any plan for porting this to python3?

**Comment by poulp** [comment]
yes i plan to migrate from pygtk to pygobject wich is compatible with both python 2 and 3. I will try to find time this week to do the migration

**Comment by khurshid-alam** [comment]
Thanks!...No Problem. Take you time.

**Comment by poulp** [comment]
it's almost done, you can use python3. i just have to fix a bug with readthedocs and it will be ok

**Comment by poulp** [comment]
python 3 is working fine and doc is ok
